wandb_version: 1

loh:
  desc: null
  value: loh
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.16.0
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: true
    start_time: 1700047109.949276
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 16
      - 23
      4: 3.10.12
      5: 0.16.0
      8:
      - 1
      - 2
      - 5
      13: linux-x86_64
